[2024-11-29T00:54:34.472+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.extract_data scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2024-11-29T00:54:34.480+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.extract_data scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2024-11-29T00:54:34.481+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-11-29T00:54:34.499+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): extract_data> on 2024-11-16 00:00:00+00:00
[2024-11-29T00:54:34.507+0000] {standard_task_runner.py:57} INFO - Started process 1311 to run task
[2024-11-29T00:54:34.510+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'extract_data', 'scheduled__2024-11-16T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/etl_bash.py', '--cfg-path', '/tmp/tmpjosdklz1']
[2024-11-29T00:54:34.511+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask extract_data
[2024-11-29T00:54:34.549+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_toll_data.extract_data scheduled__2024-11-16T00:00:00+00:00 [running]> on host ef65a0f8b8b4
[2024-11-29T00:54:34.603+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='Awana' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-16T00:00:00+00:00'
[2024-11-29T00:54:34.604+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-29T00:54:34.604+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DB0250EN-SkillsNetwork/labs/Final%20Assignment/tolldata.tgz -O /tmp/tolldata.tgz']
[2024-11-29T00:54:34.612+0000] {subprocess.py:86} INFO - Output:
[2024-11-29T00:54:34.614+0000] {subprocess.py:93} INFO - /bin/bash: line 1: wget: command not found
[2024-11-29T00:54:34.615+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-29T00:54:34.622+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-29T00:54:34.625+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=ETL_toll_data, task_id=extract_data, execution_date=20241116T000000, start_date=20241129T005434, end_date=20241129T005434
[2024-11-29T00:54:34.640+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-11-29T00:54:34.641+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2024-11-29T00:54:34.641+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-11-29T00:54:34.650+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2024-11-29T00:54:34.650+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-11-29T00:54:34.651+0000] {taskinstance.py:2005} ERROR - Failed to send email to: ['test@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2418, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2003, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-11-29T00:54:34.666+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task extract_data (Bash command failed. The command returned a non-zero exit code 127.; 1311)
[2024-11-29T00:54:34.683+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-29T00:54:34.707+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
